/*
 * Arielle
 * Sun. Nov. 27, 2016
 * Version 1.0
 * Number guessing game.
 */
package ca.hdsb.gwss.ainabe.ics3u.u5.Assignments;

/**
 *
 * @author 1ainabeari
 */
public class GuessNumber extends javax.swing.JFrame {

    /**
     * Creates new form GuessNumber
     */
    public GuessNumber() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabelRange = new javax.swing.JLabel();
        jLabelGuess = new javax.swing.JLabel();
        jLabelGuessNum = new javax.swing.JLabel();
        jTextFieldLow = new javax.swing.JTextField();
        jTextFieldHigh = new javax.swing.JTextField();
        jLabelLow = new javax.swing.JLabel();
        jLabelHigh = new javax.swing.JLabel();
        jTextFieldGuess = new javax.swing.JTextField();
        jLabelNumGuess = new javax.swing.JLabel();
        jLabelAns = new javax.swing.JLabel();
        jPanelTop = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelRanNum = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 255));

        jButton1.setText("PLAY!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelRange.setText("Enter Range of Numbers:");

        jLabelGuess.setText("Guess: ");

        jLabelGuessNum.setText("Number of Guesses");

        jTextFieldLow.setText("1");
        jTextFieldLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLowActionPerformed(evt);
            }
        });

        jTextFieldHigh.setText("100");
        jTextFieldHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHighActionPerformed(evt);
            }
        });

        jLabelLow.setText("Low");

        jLabelHigh.setText("High");

        jTextFieldGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGuessActionPerformed(evt);
            }
        });

        jLabelNumGuess.setText("0");

        jLabelAns.setText("Did you guess correctly?");

        jPanelTop.setBackground(new java.awt.Color(0, 0, 0));

        jLabelTitle.setFont(new java.awt.Font("Rod", 3, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 0, 204));
        jLabelTitle.setText("Guess Number");

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelTitle)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabelRanNum.setText("ans");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelGuessNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNumGuess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelGuess)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelRange)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldLow, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelLow))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelHigh)
                                    .addComponent(jTextFieldHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAns, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelRanNum, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(92, 92, 92))))
            .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRange)
                    .addComponent(jTextFieldLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRanNum))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLow)
                            .addComponent(jLabelHigh))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGuess)
                            .addComponent(jTextFieldGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelAns)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabelGuessNum)
                    .addComponent(jLabelNumGuess))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLowActionPerformed

    private void jTextFieldGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGuessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGuessActionPerformed

    int ranNum;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int high = Integer.parseInt(jTextFieldHigh.getText() + "");
        int low = Integer.parseInt(jTextFieldLow.getText() + "");
        int guess = Integer.parseInt(jTextFieldGuess.getText() + "");
        int numOfGuesses = Integer.parseInt(jLabelNumGuess.getText() + "");
        numOfGuesses++;
        jLabelNumGuess.setText(numOfGuesses + "");
        boolean win;
        
        // FIRST GUESS?
        if( jTextFieldHigh.isEnabled() ) {
            jTextFieldHigh.setEnabled( false );
            jTextFieldLow.setEnabled( false );
            ranNum = ran(low, high);
            jLabelRanNum.setText(ranNum + "");
        }
        
        // HIGH? LOW? RIGHT?
        check( guess, low, high );
        
        // WON!
        if (guess == ranNum){
            win(numOfGuesses, low, high);
            jLabelNumGuess.setText(numOfGuesses + "");
        }
  
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHighActionPerformed
        //High Number
        int high = Integer.parseInt(jTextFieldHigh + "");
    }//GEN-LAST:event_jTextFieldHighActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuessNumber().setVisible(true);
            }
        });
    }
    
    public static int ran(int low, int high){
        int ranNum = (int) (Math.random() * (high - low)) + low;
        return ranNum;
    }
    public void check(int guess, int low, int high ){
        if (guess < low || guess > high){
            jLabelAns.setText("INVALID GUESS, PLEASE TRY AGAIN.");
            
        }
        else if ( guess == ranNum ){
            jLabelAns.setText("Good job you answered correctly! Please play again!");
        }
        else {
            jLabelAns.setText("Sorry not quite. You are too " + wrong(ranNum, guess));
            
        }
    } 
    public static String wrong(int ranNum, int guess){
       int ans = ranNum - guess;
       if (ans > 0){
           return "low.";
       }
       else {
           return "high.";
       }
    }
    public void win(int count, int low, int high){
        jTextFieldHigh.setEnabled( true );
        jTextFieldLow.setEnabled( true );
        count = 0;
        ran(low, high);
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAns;
    private javax.swing.JLabel jLabelGuess;
    private javax.swing.JLabel jLabelGuessNum;
    private javax.swing.JLabel jLabelHigh;
    private javax.swing.JLabel jLabelLow;
    private javax.swing.JLabel jLabelNumGuess;
    private javax.swing.JLabel jLabelRanNum;
    private javax.swing.JLabel jLabelRange;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JTextField jTextFieldGuess;
    private javax.swing.JTextField jTextFieldHigh;
    private javax.swing.JTextField jTextFieldLow;
    // End of variables declaration//GEN-END:variables
}
