/*
 * Arielle
 * Mon. Nov. 28, 2016
 * Version 1.0
 * Playing rock, paper, scissors.
 */
package ca.hdsb.gwss.ainabe.ics3u.u5.Assignments;

/**
 *
 * @author 1ainabeari
 */
public class RockPaperScissors extends javax.swing.JFrame {

    /**
     * Creates new form RockPaperScissors
     */
    public RockPaperScissors() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabelComChoice = new javax.swing.JLabel();
        jLabelWin = new javax.swing.JLabel();
        jLabelWins = new javax.swing.JLabel();
        jLabelLosses = new javax.swing.JLabel();
        jLabelTies = new javax.swing.JLabel();
        jButtonPlay = new javax.swing.JButton();
        jButtonRestart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));

        jRadioButton2.setText("Scissors");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Paper");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Rock");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jLabelComChoice.setText("Computer's Choice: ");

        jLabelWin.setText("Do you Win?");

        jLabelWins.setText("Wins: 0");

        jLabelLosses.setText("Losses: 0");

        jLabelTies.setText("Ties: 0");

        jButtonPlay.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPlay.setForeground(new java.awt.Color(0, 255, 0));
        jButtonPlay.setText("Play!");
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });

        jButtonRestart.setBackground(new java.awt.Color(0, 0, 0));
        jButtonRestart.setForeground(new java.awt.Color(0, 255, 0));
        jButtonRestart.setText("Restart");
        jButtonRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelWin)
                            .addComponent(jLabelComChoice)
                            .addComponent(jLabelWins)
                            .addComponent(jLabelTies)
                            .addComponent(jLabelLosses))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(jRadioButton3)
                        .addGap(90, 90, 90)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jButtonRestart)
                    .addComponent(jButtonPlay))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelComChoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWin)
                    .addComponent(jButtonPlay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelWins)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLosses)
                    .addComponent(jButtonRestart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTies)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Freestyle Script", 0, 36)); // NOI18N
        jLabel1.setText("Rock Paper Scissors!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int com, guess;
    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
        //Variables
        com = ran();
        guess = guess();

        int win = Integer.parseInt(jLabelWins.getText().substring(6) + "");
        int loss = Integer.parseInt(jLabelLosses.getText().substring(8) + "");
        int ties = Integer.parseInt(jLabelTies.getText().substring(6) + "");

        //Enabled
        if (jRadioButton1.isSelected() || jRadioButton2.isSelected() || jRadioButton3.isSelected()) {
            jRadioButton1.setEnabled(false);
            jRadioButton2.setEnabled(false);
            jRadioButton3.setEnabled(false);
        }
        //check
        end(win, loss, ties);

        System.out.println(guess + "" + com);

    }//GEN-LAST:event_jButtonPlayActionPerformed

    private void jButtonRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestartActionPerformed
        // Reset
        jLabelWins.setText("Wins: 0");
        jLabelLosses.setText("Losses: 0");
        jLabelTies.setText("Ties: 0");
    }//GEN-LAST:event_jButtonRestartActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

        jRadioButton2.setEnabled(false);
        jRadioButton3.setEnabled(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jRadioButton1.setEnabled(false);
        jRadioButton3.setEnabled(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RockPaperScissors().setVisible(true);
            }
        });
    }

    public static String win(int com, int guess) {
        String win = "true";
        if (com == guess) {
            win = "tie";
        } else if (com == 3) {
            if (guess == 1) {
                win = "false";
            }
        } else if (com + 1 == guess) {
            win = "false";
        }
        return win;
    }

    public static int ran() {
        int ans = (int) (Math.random() * 3) + 1;
        return ans;
    }

    public int guess() {
        int ans = 0;
        if (jRadioButton1.isSelected()) {
            ans = 1;
        }
        if (jRadioButton2.isSelected()) {
            ans = 2;
        }
        if (jRadioButton3.isSelected()) {
            ans = 3;
        }
        return ans;
    }

    public static String comChoice(int com) {
        String ans = "";
        switch (com) {
            case 1:
                ans = " Rock";
                break;
            case 2:
                ans = " Scissors";
                break;
            case 3:
                ans = " Paper";
                break;
            default:
                ans = "INVALID ENTRY.";
        }

        return ans;
    }

    public void end(int win, int loss, int ties) {
        jLabelComChoice.setText("Computer's Choice: " + comChoice(com));
        if (guess == 0) {
            jLabelWin.setText(comChoice(guess));
        } else if (win(com, guess).equals("true")) {
            jLabelWin.setText("Yay," + comChoice(guess) + " beats" + comChoice(com) + ". You Win!");
            win++;

        } else if (win(com, guess).equals("false")) {
            jLabelWin.setText("Darn," + comChoice(com) + " beats" + comChoice(guess) + ". You lose. :(");
            loss++;
        } else {
            jLabelWin.setText("It's a tie!");
            ties++;
        }
        
        setButton();
        //Wins, Losses, Ties
        jLabelWins.setText("Wins: " + win);
        jLabelLosses.setText("Losses: " + loss);
        jLabelTies.setText("Ties: " + ties);
    }
    
    public void setButton(){
        //Set radio buttons
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(true);
        jRadioButton3.setEnabled(true);
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JButton jButtonRestart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelComChoice;
    private javax.swing.JLabel jLabelLosses;
    private javax.swing.JLabel jLabelTies;
    private javax.swing.JLabel jLabelWin;
    private javax.swing.JLabel jLabelWins;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
