/*
 * Arielle
 * Mon. Jan. 9, 2017.
 * Version 1.0
 * Find and add friends. 
 */
package ca.hdsb.gwss.ainabe.ics3u.u7.testCode;

import ca.hdsb.gwss.ainabe.ics3u.u7.CourseCode;
import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import nu.xom.Builder;
import nu.xom.Document;
import nu.xom.Element;
import nu.xom.Elements;
import nu.xom.ParsingException;
import nu.xom.Serializer;

/**
 *
 * @author 1ainabeari
 */
public class Friends extends javax.swing.JFrame {

    Element friends;
    Document Friends;

    /**
     * Creates new form friends
     */
    public Friends() {
        initComponents();

        File file = new File("friends.xml");
        if (file.exists()) {
            Builder builder = new Builder();
            try {
                Friends = builder.build(file);
                friends = Friends.getRootElement();
            } catch (ParsingException ex) {
                Logger.getLogger(CourseCode.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(CourseCode.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            friends = new Element("Friends");
            Friends = new Document(friends);
        }

        makeDropDown();
    }

    public void makeDropDown() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        Elements listOfFriends = friends.getChildElements();
        for( int i = 0; i < listOfFriends.size(); i++ ) {
            model.addElement( listOfFriends.get(i).getFirstChildElement("name").getValue() );
        }
        jComboBox1.setModel( model );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelAddress = new javax.swing.JLabel();
        jLabelInstagram = new javax.swing.JLabel();
        jLabelJob = new javax.swing.JLabel();
        jLabelType = new javax.swing.JLabel();
        jTextFieldAdress = new javax.swing.JTextField();
        jTextFieldInstagram = new javax.swing.JTextField();
        jTextFieldJob = new javax.swing.JTextField();
        jTextFieldType = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jLabelAdd = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jButtonConfirm = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitle.setText("Find-A-Friend");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelTitle)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Percy Jackson", "John Smith", "Natasha Rominoff" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabelAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelAddress.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAddress.setText("Address:");

        jLabelInstagram.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInstagram.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInstagram.setText("Instagram: ");

        jLabelJob.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelJob.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJob.setText("Job:");

        jLabelType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelType.setForeground(new java.awt.Color(255, 255, 255));
        jLabelType.setText("Species/Type: ");

        jTextFieldAdress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAdressFocusGained(evt);
            }
        });

        jTextFieldInstagram.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldInstagramFocusGained(evt);
            }
        });

        jTextFieldJob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldJobFocusGained(evt);
            }
        });

        jTextFieldType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldTypeFocusGained(evt);
            }
        });

        jButtonAdd.setText("Add Friend");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabelAdd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdd.setText("If you want to add a friend, fill in the boxes then press: ");

        jTextFieldName.setText("(Enter Name Here For Add Friend)");
        jTextFieldName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNameFocusGained(evt);
            }
        });
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonConfirm.setText("Confirm Edit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInstagram)
                    .addComponent(jLabelAddress)
                    .addComponent(jLabelJob)
                    .addComponent(jLabelType))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEdit))
                            .addComponent(jTextFieldJob, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldInstagram, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConfirm)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAdd)
                .addGap(26, 26, 26)
                .addComponent(jButtonAdd)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAddress)
                            .addComponent(jTextFieldAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEdit))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelInstagram)
                            .addComponent(jTextFieldInstagram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonConfirm)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJob)
                    .addComponent(jTextFieldJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelType)
                    .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jLabelAdd))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // Objects
        Elements childElements = friends.getChildElements();

        //Getting the indecies for combo box 
        int id = jComboBox1.getSelectedIndex();

        //Displaying data
        jTextFieldAdress.setText(childElements.get(id).getFirstChildElement("address").getValue());
        jTextFieldInstagram.setText(childElements.get(id).getFirstChildElement("instagram").getValue());
        jTextFieldJob.setText(childElements.get(id).getFirstChildElement("job").getValue());
        jTextFieldType.setText(childElements.get(id).getFirstChildElement("type").getValue());


    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // Objects
        Elements childElements = friends.getChildElements();

        //Elements
        Element friend = new Element("friend");
        Element name = new Element("name");
        Element address = new Element("address");
        Element instagram = new Element("instagram");
        Element job = new Element("job");
        Element type = new Element("type");
        

        //Appending
        friends.appendChild(friend);
        friend.appendChild(name);
        friend.appendChild(address);
        friend.appendChild(instagram);
        friend.appendChild(job);
        friend.appendChild(type);
        

        //Second appending
        name.appendChild(jTextFieldName.getText());
        address.appendChild(jTextFieldAdress.getText());
        instagram.appendChild(jTextFieldInstagram.getText());
        job.appendChild(jTextFieldJob.getText());
        type.appendChild(jTextFieldType.getText());

        //Serialiser
        try {
            Serializer serializer = new Serializer(System.out);
            serializer.setIndent(4);
            serializer.setMaxLength(64);
            serializer.write(Friends);
        } catch (IOException ex) {
            System.err.println(ex);
        }

        try {
            File file = new File("friends.xml");
            PrintWriter pw = new PrintWriter(file);
            BufferedWriter output = new BufferedWriter(pw);
            output.write(friends.toXML());
            output.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        makeDropDown();
        
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldAdressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAdressFocusGained
        // Make Blank
        jTextFieldAdress.setText("");
    }//GEN-LAST:event_jTextFieldAdressFocusGained

    private void jTextFieldNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNameFocusGained
        // Make Blank
        jTextFieldName.setText("");
    }//GEN-LAST:event_jTextFieldNameFocusGained

    private void jTextFieldInstagramFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldInstagramFocusGained
        // Make Blank
        jTextFieldInstagram.setText("");
    }//GEN-LAST:event_jTextFieldInstagramFocusGained

    private void jTextFieldJobFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldJobFocusGained
        // Make Blank
        jTextFieldJob.setText("");
    }//GEN-LAST:event_jTextFieldJobFocusGained

    private void jTextFieldTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTypeFocusGained
        // Make Blank
        jTextFieldType.setText("");
    }//GEN-LAST:event_jTextFieldTypeFocusGained

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Friends().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelAdd;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelInstagram;
    private javax.swing.JLabel jLabelJob;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldAdress;
    private javax.swing.JTextField jTextFieldInstagram;
    private javax.swing.JTextField jTextFieldJob;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldType;
    // End of variables declaration//GEN-END:variables
}
