/*
 * Arielle
 * Wed. Nov. 9, 2016
 * Version 1.0
 * Creating a slot machine game (GUI).
 */
package ca.hdsb.gwss.ainabe.ics3u.u4;

import java.util.Scanner;

/**
 *
 * @author 1ainabeari
 */
public class SlotMachineGUI extends javax.swing.JFrame {

    int play;
    int ran1, ran2, ran3, attempts;
    int tokens = 50;
    int count = 0;
    boolean me = false;
    int tokensWon;
    Double choice;
    
    Scanner input = new Scanner (System.in);

    /**
     * Creates new form SlotMachineGUI
     */
    public SlotMachineGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanelSlot = new javax.swing.JPanel();
        jLabelWheel1 = new javax.swing.JLabel();
        jLabelWheel2 = new javax.swing.JLabel();
        jLabelWheel3 = new javax.swing.JLabel();
        jLabelResult = new javax.swing.JLabel();
        jLabelResults = new javax.swing.JLabel();
        jLabelTokens = new javax.swing.JLabel();
        jLabelAttempts = new javax.swing.JLabel();
        jLabelWinnings = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonPlay = new javax.swing.JButton();
        jLabelLose = new javax.swing.JLabel();
        jLabelRunOut = new javax.swing.JLabel();
        jTextFieldChoice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jLabelTitle.setBackground(new java.awt.Color(255, 255, 153));
        jLabelTitle.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 0, 51));
        jLabelTitle.setText("Arielle's Slot Machine");

        jTextField1.setBackground(new java.awt.Color(51, 255, 204));
        jTextField1.setText("(｡◕‿◕｡)");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelSlot.setBackground(new java.awt.Color(51, 51, 255));

        jLabelWheel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelWheel1.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        jLabelWheel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWheel1.setText("3");
        jLabelWheel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabelWheel2.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        jLabelWheel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWheel2.setText("3");
        jLabelWheel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabelWheel3.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        jLabelWheel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWheel3.setText("3");
        jLabelWheel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabelResults.setForeground(new java.awt.Color(255, 255, 255));
        jLabelResults.setText("Your results:                                        ");
        jLabelResults.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelTokens.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTokens.setText("Tokens: ");

        jLabelAttempts.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAttempts.setText("Attempts: ");

        jLabelWinnings.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWinnings.setText("Tokens Won: ");

        javax.swing.GroupLayout jPanelSlotLayout = new javax.swing.GroupLayout(jPanelSlot);
        jPanelSlot.setLayout(jPanelSlotLayout);
        jPanelSlotLayout.setHorizontalGroup(
            jPanelSlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSlotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSlotLayout.createSequentialGroup()
                        .addComponent(jLabelResults, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelSlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSlotLayout.createSequentialGroup()
                                .addComponent(jLabelWheel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelWheel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelWheel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSlotLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelResult)))
                        .addGap(2, 2, 2))
                    .addGroup(jPanelSlotLayout.createSequentialGroup()
                        .addComponent(jLabelAttempts, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelSlotLayout.createSequentialGroup()
                        .addComponent(jLabelTokens, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jLabelWinnings)
                        .addGap(70, 70, 70))))
        );
        jPanelSlotLayout.setVerticalGroup(
            jPanelSlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSlotLayout.createSequentialGroup()
                .addGroup(jPanelSlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSlotLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanelSlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelWheel1)
                            .addComponent(jLabelWheel2)
                            .addComponent(jLabelWheel3)))
                    .addGroup(jPanelSlotLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelResults)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTokens)
                    .addComponent(jLabelWinnings))
                .addGap(18, 18, 18)
                .addComponent(jLabelAttempts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelResult)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 0, 51));

        jButtonPlay.setText("Spin");
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });

        jLabelRunOut.setText("Run out of Tokens?");

        jTextFieldChoice.setText("Enter number when prompted");
        jTextFieldChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldChoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonPlay))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLose))
                    .addComponent(jLabelRunOut))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jLabelRunOut, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLose)
                    .addComponent(jTextFieldChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButtonPlay))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSlot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSlot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
        ran1 = (int) (Math.random() * 4) + 1;
        ran2 = (int) (Math.random() * 4) + 1;
        ran3 = (int) (Math.random() * 4) + 1;
        jLabelWheel1.setText("" + ran1);
        jLabelWheel2.setText("" + ran2);
        jLabelWheel3.setText("" + ran3);
        
        //Winnings
        if (ran1 != ran2 || ran2 != ran3) {
                    tokens -= 1;
                    jLabelResults.setText("Results: Lose");
                    jLabelTokens.setText("Tokens: " + tokens);
                    jLabelWinnings.setText("Tokens Won: 0");
                } else {
                    switch (ran1) {
                        case 1:
                            tokens += 3;
                            break;
                        case 2:
                            tokens += 5;
                            break;
                        case 3:
                            tokens += 7;
                            break;
                        case 4:
                            tokens += 9;
                            break;

                    }
                    tokensWon = ran1 * 2 + 2;
                    jLabelResults.setText("Results: " + "Win");
                    jLabelTokens.setText("Tokens: " + tokens);
                    jLabelWinnings.setText("Tokens Won: " + tokensWon);

                }
        //Counter
        attempts ++;
        jLabelAttempts.setText("Attempts:" + attempts);
        
        if (tokens < 1){

                jLabelRunOut.setText("Out of tokens please enter 1 to restart");
                choice  = Double.parseDouble(jTextFieldChoice.getText());
                if (choice == 1){
                    jLabelRunOut.setText("Press spin to reset, then press again to play.");
                    jLabelTokens.setText("Tokens: 50");
                    tokens = 50;
                }
                jLabelRunOut.setText("Run out of Tokens?");

           
        }
       
                
 
    }//GEN-LAST:event_jButtonPlayActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextFieldChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldChoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlotMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlotMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlotMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlotMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlotMachineGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JLabel jLabelAttempts;
    private javax.swing.JLabel jLabelLose;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JLabel jLabelResults;
    private javax.swing.JLabel jLabelRunOut;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTokens;
    private javax.swing.JLabel jLabelWheel1;
    private javax.swing.JLabel jLabelWheel2;
    private javax.swing.JLabel jLabelWheel3;
    private javax.swing.JLabel jLabelWinnings;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelSlot;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldChoice;
    // End of variables declaration//GEN-END:variables
}
